name: Blank Issue Form
description: 'BetterVoting issue form'
labels: ['Role: Missing', 'Complexity: Missing']
projects: ['Equal-Vote/3']

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less (ex. We need to do X because of Y)
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues"
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
  - type: checkboxes
    id: confirm-label
    attributes:
      label: I have set labels for the following [more labels info](https://docs.bettervoting.com/contributions/4_issue_lifecycle.html#issue-labels)
      options:
        - label: "Role" # These quotes are needed for some reason
          required: true
        - label: "Complexity" # These quotes are needed for some reason
          required: true
