name: Emergent Request
description: When you discover something in your issue that is out of scope and it needs a new issue or discussion
labels: ['Role: Missing', 'Complexity: Missing', 'Missing Milestone', 'ER']

body:
  - type: textarea
    id: overview
    attributes:
      label: Emergent Requirement - Problem
      description: Describe the problem you encountered
    validations:
      required: true
  - type: textarea # I'm using a text area since auto complete doesn't work on input
    id: where
    attributes:
      label: Link to issue you discovered this emergent requirement in
      placeholder: '#811'
  - type: input
    id: date
    attributes:
      label: Date discovered
      placeholder: October 8 2025
    validations:
      required: true
  - type: textarea
    id: temporary
    attributes:
      label: Describe any temporary measures that needed to be taken
      value: "None"
  - type: textarea # I'm using a text area since auto complete doesn't work on input
    id: who
    attributes:
      label: Who was involved?
      placeholder: "ex. @ArendPeter @masiarek"
  - type: textarea
    id: risk
    attributes:
      label: What happens if this is not addressed?
  - type: textarea
    id: resources
    attributes:
      label: Resources
  - type: checkboxes
    attributes:
      label: Recommended Action Items
      options:
        - label: Make a new issue
        - label: Discuss with team
        - label: Let a Dev Lead know
  - type: textarea
    attributes:
      label: Potential solutions [draft]